version: "3.9"
services:
  web:
    build: .
    stdin_open: true
    tty: true
    command:
      - /bin/bash
      - -c
      - |
        bin/run
    ports:
      - "80:8000"
    volumes:
      - .:/django_skeleton
